Repository TriBITSPub/TriBITS, pull requests merged in 2021-07, with the labels that each got.

#390 Add test for doc generation and fix usage of Python3
  dev_testing/crf450/checkin-test-crf450-cmake-3.17.0-python-3.5.2.sh
  dev_testing/crf450/checkin-test-crf450-cmake-3.17.0.sh
  dev_testing/crf450/mpi-debug/do-configure
  test/CMakeLists.txt
  test/doc/CMakeLists.txt
  tribits/doc/build_ref/create-project-build-ref.py
Labels: component: documentation, type: bug

#391 Fix up build_docs.sh for Sphinx doc generation (#386)
  test/doc/CMakeLists.txt
  tribits/doc/build_docs.sh
  tribits/doc/build_ref/create-build-ref.sh
  tribits/doc/guides/generate-guide.sh
Labels: component: documentation, type: enhancement

#392 Fix broken tests for non-Fortran and CMake 3.21 builds (#363)
  dev_testing/crf450/mpi-debug/do-configure
  test/core/ExamplesUnitTests/CMakeLists.txt
  test/ctest_driver/TribitsExampleMetaProject/CMakeLists.txt
  test/ctest_driver/TribitsExampleProject/CMakeLists.txt
  tribits/core/config_tests/fmangle/CMakeLists.txt
  tribits/core/package_arch/TribitsAddInstallGroupAndPermsFixups.cmake
Labels: component: core

#393 GitHub Actions based testing for TriBITS (#363)
  .github/workflows/hellow_world.yml
  .github/workflows/tribits_testing.yml
  cmake/ctest/github_actions/ctest_github_actions_serial_debug.cmake
  cmake/ctest/github_actions/run_github_actions_ctest_driver.sh
  cmake/ctest/github_actions/tribits_cmake-3.21.0_makefiles_python-3.8_g++-9_tweaks.cmake
Labels: type: enhancement

#396 Send PR results to 'Pull Request' CDash group and add PR ID to build names (#363)
  cmake/ctest/github_actions/run_github_actions_ctest_driver.sh
Labels: type: enhancement

#398 Deal with pr null in not preprending build name (#363)
  cmake/ctest/github_actions/run_github_actions_ctest_driver.sh
Labels: type: bug

#387 Build and deploy TriBITS documentation with Sphinx (#386)
  .github/workflows/deploy_docs.yml
  .gitignore
  test/doc/CMakeLists.txt
  test/doc/FindTestDocDir.py
  test/doc/data/TribitsGuidesBody.rst
  test/doc/sphinx_rst_generator_UnitTests.py
  tribits/doc/build_ref/Makefile
  tribits/doc/build_ref/create-build-ref.sh
  tribits/doc/sphinx/build_ref/Makefile
  tribits/doc/sphinx/build_ref/__init__.py
  tribits/doc/sphinx/build_ref/conf.py
  tribits/doc/sphinx/build_ref/make.bat
  tribits/doc/sphinx/build_sphinx_docs.sh
  tribits/doc/sphinx/combined_docs/index.html
  tribits/doc/sphinx/index.rst
  tribits/doc/sphinx/maintainers_guide/Makefile
  tribits/doc/sphinx/maintainers_guide/__init__.py
  tribits/doc/sphinx/maintainers_guide/conf.py
  tribits/doc/sphinx/maintainers_guide/make.bat
  tribits/doc/sphinx/requirements.txt
  tribits/doc/sphinx/sphinx_rst_generator.py
  tribits/doc/sphinx/users_guide/Makefile
  tribits/doc/sphinx/users_guide/__init__.py
  tribits/doc/sphinx/users_guide/conf.py
  tribits/doc/sphinx/users_guide/make.bat
Labels: component: documentation, type: enhancement
