Repository TriBITSPub/TriBITS, pull requests merged in 2022-03, with the labels that each got.

#456 Add support for <Project>_IMPORTED_NO_SYSTEM and related (#443)
  test/core/ExamplesUnitTests/TribitsExampleApp_Tests.cmake
  test/core/ExamplesUnitTests/TribitsExampleProject_Tests.cmake
  tribits/CHANGELOG.md
  tribits/ReleaseNotes.txt
  tribits/core/package_arch/TribitsGlobalMacros.cmake
  tribits/core/package_arch/TribitsLibraryMacros.cmake
  tribits/core/package_arch/TribitsPackageMacros.cmake
  tribits/doc/build_ref/TribitsBuildReferenceBody.rst
  tribits/doc/guides/Makefile.common_generated_files
  tribits/doc/guides/TribitsCoreDetailedReference.rst
Labels: type: enhancement, component: core

#457 Enable CMake 3.23.0-rc2 build
  .github/workflows/tribits_testing.yml
Labels: type: enhancement, component: testing

#459 Better document <Project>_IMPORTED_NO_SYSTEM and workarounds (#443)
  tribits/CHANGELOG.md
  tribits/doc/build_ref/TribitsBuildReferenceBody.rst
  tribits/doc/guides/TribitsCoreDetailedReference.rst
Labels: type: enhancement, component: documentation, component: core

#463 #433: Fixed typos in docs
  tribits/core/package_arch/TribitsPackageMacros.cmake
  tribits/core/package_arch/TribitsWriteClientExportFiles.cmake
Labels: component: documentation

#470 Add git fetch to fix git desribe (#465)
  .github/workflows/deploy_docs.yml
Labels: type: bug, component: documentation

#471 Add example for <packageName>_config.h.in file (#299)
  tribits/core/package_arch/TribitsPackageMacros.cmake
  tribits/doc/guides/TribitsGuidesBody.rst
Labels: type: enhancement, component: documentation

#469 Expand TribitsExampleProject2 packages and TPLs (#299)
  test/core/ExamplesUnitTests/CommonArgumentsCMakeProjects.cmake
  test/core/ExamplesUnitTests/TribitsExampleApp2_Tests.cmake
  test/core/ExamplesUnitTests/TribitsExampleProject2_Tests.cmake
  test/core/ExamplesUnitTests/TribitsExampleProject2_Tpls_Install_Tests.cmake
  test/core/ExamplesUnitTests/TribitsExampleProject_Tests.cmake
  test/core/TestingFunctionMacro_UnitTests.cmake
  tribits/core/package_arch/TribitsTplFindIncludeDirsAndLibraries.cmake
  tribits/doc/build_ref/TribitsBuildReferenceBody.rst
  tribits/examples/TribitsExampleApp2/AppHelperFuncs.cmake
  tribits/examples/TribitsExampleApp2/app.cpp
  tribits/examples/TribitsExampleProject2/PackagesList.cmake
  tribits/examples/TribitsExampleProject2/TPLsList.cmake
  tribits/examples/TribitsExampleProject2/cmake/tpls/FindTPLTpl2.cmake
  tribits/examples/TribitsExampleProject2/cmake/tpls/FindTPLTpl3.cmake
  tribits/examples/TribitsExampleProject2/cmake/tpls/FindTPLTpl4.cmake
  tribits/examples/TribitsExampleProject2/packages/package1/src/Package1.cpp
  tribits/examples/TribitsExampleProject2/packages/package1/src/Package1.hpp
  tribits/examples/TribitsExampleProject2/packages/package2/CMakeLists.txt
  tribits/examples/TribitsExampleProject2/packages/package2/cmake/Dependencies.cmake
  tribits/examples/TribitsExampleProject2/packages/package2/src/CMakeLists.txt
  tribits/examples/TribitsExampleProject2/packages/package2/src/Package2.cpp
  tribits/examples/TribitsExampleProject2/packages/package2/src/Package2.hpp
  tribits/examples/TribitsExampleProject2/packages/package2/src/Package2_Prg.cpp
  tribits/examples/TribitsExampleProject2/packages/package2/test/CMakeLists.txt
  tribits/examples/TribitsExampleProject2/packages/package3/CMakeLists.txt
  tribits/examples/TribitsExampleProject2/packages/package3/cmake/Dependencies.cmake
  tribits/examples/TribitsExampleProject2/packages/package3/src/CMakeLists.txt
  tribits/examples/TribitsExampleProject2/packages/package3/src/Package3.cpp
  tribits/examples/TribitsExampleProject2/packages/package3/src/Package3.hpp
  tribits/examples/TribitsExampleProject2/packages/package3/src/Package3_Prg.cpp
  tribits/examples/TribitsExampleProject2/packages/package3/test/CMakeLists.txt
  tribits/examples/tpls/Tpl2/CMakeLists.txt
  tribits/examples/tpls/Tpl2/Tpl2Config.cmake.in
  tribits/examples/tpls/Tpl2/Tpl2a.cpp
  tribits/examples/tpls/Tpl2/Tpl2a.hpp
  tribits/examples/tpls/Tpl2/Tpl2b.cpp
  tribits/examples/tpls/Tpl2/Tpl2b.hpp
  tribits/examples/tpls/Tpl3/CMakeLists.txt
  tribits/examples/tpls/Tpl3/Tpl3.cpp
  tribits/examples/tpls/Tpl3/Tpl3.hpp
  tribits/examples/tpls/Tpl3/Tpl3Config.cmake.in
  tribits/examples/tpls/Tpl4/CMakeLists.txt
  tribits/examples/tpls/Tpl4/Tpl4.hpp
  tribits/examples/tpls/Tpl4/Tpl4Config.cmake.in
Labels: component: documentation, component: core, component: testing

#475 Fix some typos and set up for aspell checking (#473)
  tribits/doc/guides/TribitsGuidesBody.rst
Labels: type: bug, component: documentation

#477 Fix some more typos and set up for aspell checking (#473)
  tribits/doc/guides/TribitsGuidesBody.rst
Labels: type: bug, component: documentation
